### PR TITLE
Some initial MathUtil tests

### PR DESCRIPTION
**Pull request by MatthewMerrill**
Tests:
 - MathUtil#mean
 - MathUtil#roundToPlace

### CODE REVIEW

**Comment by MatthewMerrill** [comment]
nooooooooooo

**Comment by MatthewMerrill** [comment]
lol

**Comment by aryue123321** [comment]
no what, lol

**Comment by MatthewMerrill** [comment]
I shouldn't have had the yarn in there lol I'll send another PR to fix

**Pull request merged**
