### PR TITLE
Mocha chai testing

### PR DESCRIPTION
**Pull request by aryue123321**
Converted one-proportion based on Matt's setup.
Added mocha-chai

### CODE REVIEW

**Comment by MatthewMerrill** [comment]
Does this build?

**Comment by aryue123321** [comment]
> Does this build?

Netify failed.....
is it because it has both npm and jeykll?

**Comment by MatthewMerrill** [comment]
I think I might need to reconfigure netlify with the change... I'll try adding the configuration in a commit and I'll merge it onto this branch

**Comment by aryue123321** [comment]
yeah, just google it, configure netify to Jekyll, on github, finding the password now....do that after dinner

**Comment by MatthewMerrill** [comment]
Woohoo! Passes now.

**Comment by aryue123321** [comment]
GOGOG)!!!

**Pull request merged**
